---
owner: lwbt # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
sites:
  - name: Google
    url: https://www.google.com
  - name: Uptime Kuma
    url: https://uptime.astrapia-mermaid.ts.net/
status-website:
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Monitor
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
      # - title: GitHub
      #   href: https://github.com/$OWNER/$REPO
# NOTE:
# The documentation claims that GitHub Actions can run no faster than every 5
# minutes. Actual data suggests that Actions run at 30 minutes granularity in
# 2025.
workflowSchedule:
  # graphs: "0 0 * * *"
  # responseTime: "0 23 * * *"
  # staticSite: "0 1 * * *"
  # summary: "0 0 * * *"
  # updateTemplate: "0 0 * * *"
  # NOTE:
  # Updates are supposed to run once per week, but it runs every day?
  # https://upptime.js.org/docs/triggers/#update-template-ci
  # Try to run it during the holidays while to keep noise to a minimum while I
  # try to figure out how the resolve issues that require editing template
  # code.
  updateTemplate: "0 14 25-31 12 6"
  # updates: "0 3 * * *"
  # uptime: "*/5 * * * *"
  # Once or twice per hour should be enough for my needs.
  uptime: "*/30 * * * *"
# TODO:
# runner: "[self-hosted, Linux, X64]"
# runner: '[self-hosted, linux, X64, futro]'
runner: '[self-hosted, linux, X64]'

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
